
export type BreakpointRefTypes = "breakpoints.xs"
   | "breakpoints.sm"
   | "breakpoints.md"
   | "breakpoints.lg"
   | "breakpoints.xl";

export type TextRefTypes = "subtitle"
   | "body"
   | "button"
   | "h1"
   | "h2"
   | "h3"
   | "h4"
   | "h5"
   | "h6";


export type ColorsRefTypes = "background.default"
   | "background.paper"
   | "primary"
   | "primary.main"
   | "primary.light"
   | "primary.dark"
   | "primary.text"
   | "secondary"
   | "secondary.main"
   | "secondary.light"
   | "secondary.dark"
   | "secondary.text"
   | "success"
   | "success.main"
   | "success.light"
   | "success.dark"
   | "success.text"
   | "error"
   | "error.main"
   | "error.light"
   | "error.dark"
   | "error.text"
   | "warning"
   | "warning.main"
   | "warning.light"
   | "warning.dark"
   | "warning.text"
   | "text"
   | "text.primary"
   | "text.secondary"
   | "text.disabled"
   | "divider"
   | "divider.main"
   | "divider.light"
   | "divider.dark"
   | "grey.1"
   | "grey.2"
   | "grey.3"
   | "grey.4"
   | "grey.5"
   | "grey.6"
   | "grey.7"
   | "grey.8"
   | "grey.9"
   | "grey.10"


export type ShadowRefTyeps = "shadow.1"
   | "shadow.2"
   | "shadow.3"
   | "shadow.4"
   | "shadow.5"
   | "shadow.6"
   | "shadow.7"
   | "shadow.8"
   | "shadow.9"
   | "shadow.10";

export type RadiusRefTyeps = "radius.1"
   | "radius.2"
   | "radius.3"
   | "radius.4"
   | "radius.5"