
export type BreakpointRefTypes = "breakpoints.xs"
   | "breakpoints.sm"
   | "breakpoints.md"
   | "breakpoints.lg"
   | "breakpoints.xl";

export type TextRefTypes = "title"
   | "subtitle"
   | "pragraph"
   | "button"
   | "h1"
   | "h2"
   | "h3"
   | "h4"
   | "h5"
   | "h6";


export type ColorsRefTypes = "background"
   | "background.main"
   | "background.light"
   | "background.dark"
   | "background.text"
   | "primary"
   | "primary.main"
   | "primary.light"
   | "primary.dark"
   | "primary.text"
   | "secondary"
   | "secondary.main"
   | "secondary.light"
   | "secondary.dark"
   | "secondary.text"
   | "success"
   | "success.main"
   | "success.light"
   | "success.dark"
   | "success.text"
   | "error"
   | "error.main"
   | "error.light"
   | "error.dark"
   | "error.text"
   | "warning"
   | "warning.main"
   | "warning.light"
   | "warning.dark"
   | "warning.text"
   | "info"
   | "info.main"
   | "info.light"
   | "info.dark"
   | "info.text"
   | "text"
   | "text.main"
   | "text.light"
   | "text.dark"
   | "text.text"
   | "divider"
   | "divider.main"
   | "divider.light"
   | "divider.dark"
   | "divider.divider";


export type ShadowRefTyeps = "shadow.1"
   | "shadow.2"
   | "shadow.3"
   | "shadow.4"
   | "shadow.5"
   | "shadow.6"
   | "shadow.7"
   | "shadow.8"
   | "shadow.9"
   | "shadow.10";